name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
      types:
        - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull skye0814/sems-api:latest
    - name: Delete old docker container
      run: sudo docker rm -f sems-api-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 80:80 --name sems-api-container skye0814/sems-api
